# https://squidfunk.github.io/mkdocs-material/reference/
nav:
  - Home: index.md
  - Importing: importing.md
  - Detecting Cuts: detecting_cuts.md
  - Shots Table: shots_table.md
  - Spike Graph: spike_graph.md
  - Contact Sheet: contact_sheet.md
  - Manual Edits: manual_edits.md
  - Exporting: exporting.md
  - Integrations:
      - Hiero: hiero.md


site_name: CutDetector Docs
site_url: https://cutdetector.readthedocs.io/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: teal
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: deep orange
      accent: deep orange

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - attr_list
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3NBMJNbHaP

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/glightbox-gallery.js

plugins:
  - glightbox
  - search

copyright: Copyright &copy; 2026 Frank Rueter | OHUfx